source "https://rubygems.org"

gem "sinatra", "2.0.7"
gem "sinatra-contrib", "2.0.7"
gem "puma", "4.3.3"
gem "pry"
gem "rack-test"
gem "httparty"
gem "sir_model"
gem "restcountry"
gem "pomber_covid19", "0.1.3"
